"""add chat focus areas

Revision ID: 3b4a83deaede
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 12:27:59.040826
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4a83deaede'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_focus_areas',
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_session_id', 'node_id')
    )
    op.create_index('chat_focus_areas_session_idx', 'chat_focus_areas', ['chat_session_id'], unique=False)
    
    # Enable RLS
    op.execute("ALTER TABLE chat_focus_areas ENABLE ROW LEVEL SECURITY")
    
    # Create RLS Policy
    op.execute(
        """
        CREATE POLICY "Users can manage their own chat focus area selections"
        ON chat_focus_areas FOR ALL USING (
            EXISTS (SELECT 1 FROM chat_sessions cs WHERE cs.id = chat_session_id AND cs.user_id = auth.uid())
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS \"Users can manage their own chat focus area selections\" ON chat_focus_areas")
    op.drop_index('chat_focus_areas_session_idx', table_name='chat_focus_areas')
    op.drop_table('chat_focus_areas')
    # ### end Alembic commands ###
