"""Add tracking columns to document_uploads

Revision ID: ea1a3304ef3f
Revises: 
Create Date: 2026-06-10 14:22:58.573993
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1a3304ef3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_uploads', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('document_uploads', sa.Column('toc_method_used', sa.String(), nullable=True))
    op.add_column('document_uploads', sa.Column('hierarchy_node_count', sa.Integer(), nullable=True))
    op.add_column('document_uploads', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('document_uploads', sa.Column('processing_time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_uploads', 'processing_time_seconds')
    op.drop_column('document_uploads', 'chunk_count')
    op.drop_column('document_uploads', 'hierarchy_node_count')
    op.drop_column('document_uploads', 'toc_method_used')
    op.drop_column('document_uploads', 'document_type')
    # ### end Alembic commands ###
